from __future__ import annotations

import argparse
import json
import random
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from PIL import Image
from PIL import ImageOps

SCRIPT_DIR = Path(__file__).resolve().parent
PY_ROOT = SCRIPT_DIR.parent
if str(PY_ROOT) not in sys.path:
    sys.path.insert(0, str(PY_ROOT))

from app.core.database import ensure_db
from app.core.database import open_db
from app.services.community_seed import _comment_templates_for_category
from app.services.community_seed import _refresh_counts
from app.services.community_seed import _tip_text_for_category
from app.services.community_service import _ensure_safe_text
from app.services.community_service import _normalize_caption
from app.services.community_service import _normalize_place_tag
from app.services.community_service import _normalize_review
from app.services.community_service import _normalize_scene_type

_NICKNAME_POOL = [
    "阿澄",
    "木糖",
    "晚星",
    "橘子汽水",
    "小岚",
    "南枝",
    "遥遥",
    "阿宁",
    "云朵",
    "Mika",
    "可栗",
    "青禾",
    "阿眠",
    "星野",
    "知夏",
    "沐沐",
    "十一",
    "Luna",
    "Nora",
    "Yuki",
    "迟迟",
    "可颂",
    "柚白",
    "安可",
    "阿芙",
    "鲸鱼汽水",
    "枝枝",
    "Momo",
    "Sia",
    "盐汽水",
]

_SUPPORTED_EXTS = {".jpg", ".jpeg", ".png", ".webp"}
_BLOCK_HEADER_RE = re.compile(r"^\s*(?:===\s*(.+?)\s*===|\[(.+?)\])\s*$")


@dataclass
class ParsedMetadata:
    filename: str
    nickname: str
    primary_category: str
    scene_type: str
    place_tag: str
    caption: str
    review_text: str
    rating: int
    tags: list[str]
    like_count: int
    comment_count: int
    comments: list[str]
    captured_at: str


@dataclass
class ImportedPost:
    post_id: int
    user_id: int
    nickname: str
    primary_category: str
    place_tag: str
    created_at: int
    like_count: int
    comment_count: int
    comments: list[str]


def main() -> None:
    parser = argparse.ArgumentParser(description="Import folder photos into community posts from a GPT-generated txt file.")
    parser.add_argument(
        "--photo-dir",
        default=r"C:\Users\zixia\Desktop\photoes",
        help="Folder containing source photos.",
    )
    parser.add_argument(
        "--metadata-file",
        default="",
        help="Txt metadata file generated by GPT. Supports JSON or block text format.",
    )
    parser.add_argument(
        "--email-prefix",
        default="photo_import",
        help="Prefix for generated import users.",
    )
    parser.add_argument(
        "--batch-label",
        default="photoes_batch",
        help="Batch label written into feedback session_meta.",
    )
    parser.add_argument(
        "--write-template",
        default="",
        help="Write an empty txt template for the folder and exit.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Only import the first N photos. 0 means all.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=20260407,
        help="Random seed for deterministic like/comment distribution.",
    )
    parser.add_argument(
        "--keep-old-imports",
        action="store_true",
        help="Keep existing imported users/posts for the same email prefix instead of clearing them first.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and validate only, do not write database records.",
    )
    args = parser.parse_args()

    photo_dir = Path(args.photo_dir).expanduser().resolve()
    if not photo_dir.exists() or not photo_dir.is_dir():
        raise SystemExit(f"photo dir not found: {photo_dir}")

    photo_paths = _list_photo_paths(photo_dir, limit=args.limit)
    if not photo_paths:
        raise SystemExit(f"no supported images found in: {photo_dir}")

    if args.write_template:
        template_path = Path(args.write_template).expanduser().resolve()
        template_path.write_text(_build_template_text(photo_paths), encoding="utf-8")
        print(f"template written: {template_path}")
        return

    if not args.metadata_file:
        raise SystemExit("metadata file is required unless --write-template is used")

    metadata_path = Path(args.metadata_file).expanduser().resolve()
    if not metadata_path.exists():
        raise SystemExit(f"metadata file not found: {metadata_path}")

    parsed_items = _load_metadata_items(metadata_path)
    metadata_by_name = {item.filename: item for item in parsed_items}
    missing = [path.name for path in photo_paths if path.name not in metadata_by_name]
    if missing:
        raise SystemExit(f"metadata missing for files: {', '.join(missing)}")

    ensure_db()
    if args.dry_run:
        print(f"validated {len(photo_paths)} photos with metadata from {metadata_path}")
        return

    rng = random.Random(args.seed)
    conn = open_db()
    try:
        if not args.keep_old_imports:
            _clear_previous_imports(conn, email_prefix=args.email_prefix)

        imported_posts: list[ImportedPost] = []
        used_nicknames: set[str] = set()

        for index, photo_path in enumerate(photo_paths):
            metadata = metadata_by_name[photo_path.name]
            user = _ensure_import_user(
                conn=conn,
                email_prefix=args.email_prefix,
                ordinal=index + 1,
                nickname=metadata.nickname,
                created_at=_pick_created_at(metadata.captured_at, photo_path, index=index),
                used_nicknames=used_nicknames,
            )
            created_at = _pick_created_at(metadata.captured_at, photo_path, index=index)
            image_bytes = _normalize_image_bytes(photo_path)
            upload_path = _save_import_image_bytes(photo_dir=photo_path.parent, image_name=photo_path.name, image_bytes=image_bytes)
            feedback_id = _insert_feedback(
                conn=conn,
                user_id=user["id"],
                photo_path=photo_path,
                metadata=metadata,
                created_at=created_at,
                batch_label=args.batch_label,
            )
            post_id = _insert_post(
                conn=conn,
                user_id=user["id"],
                feedback_id=feedback_id,
                upload_path=upload_path,
                image_bytes=image_bytes,
                metadata=metadata,
                created_at=created_at,
            )
            imported_posts.append(
                ImportedPost(
                    post_id=post_id,
                    user_id=user["id"],
                    nickname=user["nickname"],
                    primary_category=metadata.primary_category,
                    place_tag=metadata.place_tag,
                    created_at=created_at,
                    like_count=metadata.like_count,
                    comment_count=metadata.comment_count,
                    comments=metadata.comments,
                )
            )

        _populate_engagement(conn=conn, imported_posts=imported_posts, rng=rng)
        _refresh_counts(conn)
        conn.commit()

        print(f"imported posts: {len(imported_posts)}")
        for item in imported_posts:
            print(
                f"post_id={item.post_id} user={item.nickname} "
                f"likes={item.like_count} comments={item.comment_count} place={item.place_tag}"
            )
    finally:
        conn.close()


def _list_photo_paths(photo_dir: Path, limit: int) -> list[Path]:
    paths = [path for path in sorted(photo_dir.iterdir()) if path.is_file() and path.suffix.lower() in _SUPPORTED_EXTS]
    if limit > 0:
        return paths[:limit]
    return paths


def _build_template_text(photo_paths: list[Path]) -> str:
    blocks: list[str] = [
        "# Put one block per image. Keep the filename exactly the same as the real file.",
        "# You can let GPT fill this txt and then run the import script.",
        "# Supported keys: nickname, primary_category, scene_type, place_tag, caption, review_text, rating,",
        "# tags, like_count, comment_count, captured_at, comments.",
        "# comments supports bullet lines under the key.",
        "",
    ]
    for path in photo_paths:
        blocks.extend(
            [
                f"=== {path.name} ===",
                "nickname:",
                "primary_category:",
                "scene_type:",
                "place_tag:",
                "caption:",
                "review_text:",
                "rating: 4",
                "tags:",
                "like_count: 8",
                "comment_count: 3",
                "captured_at:",
                "comments:",
                "- ",
                "- ",
                "- ",
                "",
            ]
        )
    return "\n".join(blocks).strip() + "\n"


def _load_metadata_items(metadata_path: Path) -> list[ParsedMetadata]:
    raw = metadata_path.read_text(encoding="utf-8").lstrip("\ufeff").strip()
    if not raw:
        raise SystemExit("metadata file is empty")

    parsed = _try_parse_json_payload(raw)
    if parsed is None:
        parsed = _parse_text_blocks(raw)

    items: list[ParsedMetadata] = []
    for raw_item in parsed:
        item = _normalize_metadata_item(raw_item)
        items.append(item)
    return items


def _try_parse_json_payload(raw: str) -> list[dict[str, Any]] | None:
    candidate_texts = [raw]
    fenced = re.findall(r"```(?:json)?\s*(.*?)```", raw, flags=re.DOTALL | re.IGNORECASE)
    candidate_texts.extend(chunk.strip() for chunk in fenced if chunk.strip())

    for candidate in candidate_texts:
        try:
            payload = json.loads(candidate)
        except Exception:
            continue
        if isinstance(payload, dict):
            items = payload.get("items")
            if isinstance(items, list):
                return [item for item in items if isinstance(item, dict)]
        if isinstance(payload, list):
            return [item for item in payload if isinstance(item, dict)]
    return None


def _parse_text_blocks(raw: str) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    in_comments = False
    comment_prefixes = ("-", "*", "•")

    for line in raw.splitlines():
        header_match = _BLOCK_HEADER_RE.match(line)
        if header_match:
            if current is not None:
                items.append(current)
            filename = (header_match.group(1) or header_match.group(2) or "").strip()
            current = {"filename": filename, "comments": []}
            in_comments = False
            continue

        if current is None:
            continue

        stripped = line.strip()
        if not stripped:
            # Allow blank separator lines inside the comments block.
            continue

        if in_comments and stripped.startswith(comment_prefixes):
            comment = stripped[1:].strip()
            if comment:
                current.setdefault("comments", []).append(comment)
            continue

        if ":" not in stripped:
            continue

        key, value = stripped.split(":", 1)
        key = key.strip().lower()
        value = value.strip()
        if key == "comments":
            in_comments = True
            if value:
                current.setdefault("comments", []).append(value)
            continue
        if key == "tags":
            current[key] = [token.strip() for token in re.split(r"[|,，/]+", value) if token.strip()]
            continue
        current[key] = value
        in_comments = False

    if current is not None:
        items.append(current)
    return items


def _normalize_metadata_item(raw: dict[str, Any]) -> ParsedMetadata:
    filename = str(raw.get("filename") or raw.get("source_name") or "").strip()
    if not filename:
        raise SystemExit("every metadata item must contain filename/source_name")

    primary_category = _normalize_primary_category(str(raw.get("primary_category") or "general"))
    scene_type = _normalize_scene_type(_map_scene_type(str(raw.get("scene_type") or primary_category)))
    place_tag = _normalize_place_tag(str(raw.get("place_tag") or _default_place_tag(primary_category)))
    caption = _normalize_caption(str(raw.get("caption") or _default_caption(primary_category, place_tag)))
    review_text = _normalize_review(str(raw.get("review_text") or _default_review(primary_category, place_tag)))
    nickname = _normalize_nickname(str(raw.get("nickname") or ""))
    rating = _clamp_int(raw.get("rating"), default=_default_rating(primary_category), min_value=1, max_value=5)

    tags_raw = raw.get("tags") or []
    if isinstance(tags_raw, str):
        tags = [token.strip() for token in re.split(r"[|,，/]+", tags_raw) if token.strip()]
    else:
        tags = [str(token).strip() for token in tags_raw if str(token).strip()]

    comments_raw = raw.get("comments") or []
    if isinstance(comments_raw, str):
        comments = [token.strip() for token in re.split(r"\|\||[|；;]", comments_raw) if token.strip()]
    else:
        comments = [str(token).strip() for token in comments_raw if str(token).strip()]

    like_count = _clamp_int(raw.get("like_count"), default=_default_like_count(primary_category), min_value=0, max_value=99)
    comment_count = _clamp_int(raw.get("comment_count"), default=max(1, min(6, len(comments) or 3)), min_value=0, max_value=20)
    captured_at = str(raw.get("captured_at") or "").strip()

    _ensure_safe_text(place_tag)
    _ensure_safe_text(caption)
    _ensure_safe_text(review_text)
    for comment in comments:
        _ensure_safe_text(comment)

    return ParsedMetadata(
        filename=filename,
        nickname=nickname,
        primary_category=primary_category,
        scene_type=scene_type,
        place_tag=place_tag,
        caption=caption,
        review_text=review_text,
        rating=rating,
        tags=tags,
        like_count=like_count,
        comment_count=comment_count,
        comments=comments,
        captured_at=captured_at,
    )


def _clear_previous_imports(conn: Any, email_prefix: str) -> None:
    rows = conn.execute(
        "SELECT id FROM users WHERE email LIKE ? ORDER BY id",
        (f"{email_prefix}_%@cammate.local",),
    ).fetchall()
    user_ids = [int(row["id"]) for row in rows]
    if not user_ids:
        return

    placeholders = ",".join("?" for _ in user_ids)
    post_rows = conn.execute(
        f"SELECT id FROM community_posts WHERE user_id IN ({placeholders})",
        tuple(user_ids),
    ).fetchall()
    post_ids = [int(row["id"]) for row in post_rows]

    if post_ids:
        post_placeholders = ",".join("?" for _ in post_ids)
        image_rows = conn.execute(
            f"SELECT image_path FROM community_posts WHERE id IN ({post_placeholders})",
            tuple(post_ids),
        ).fetchall()
        for row in image_rows:
            _delete_local_file(str(row["image_path"] or ""))
        conn.execute(
            f"DELETE FROM community_post_likes WHERE post_id IN ({post_placeholders})",
            tuple(post_ids),
        )
        conn.execute(
            f"DELETE FROM community_post_comments WHERE post_id IN ({post_placeholders})",
            tuple(post_ids),
        )
        conn.execute(
            f"DELETE FROM community_post_signals WHERE post_id IN ({post_placeholders})",
            tuple(post_ids),
        )
        conn.execute(
            f"DELETE FROM community_post_reports WHERE post_id IN ({post_placeholders})",
            tuple(post_ids),
        )
        conn.execute(
            f"DELETE FROM community_creative_jobs WHERE reference_post_id IN ({post_placeholders})",
            tuple(post_ids),
        )
        conn.execute(
            f"DELETE FROM community_posts WHERE id IN ({post_placeholders})",
            tuple(post_ids),
        )

    conn.execute(
        f"DELETE FROM community_post_likes WHERE user_id IN ({placeholders})",
        tuple(user_ids),
    )
    conn.execute(
        f"DELETE FROM community_post_comments WHERE user_id IN ({placeholders})",
        tuple(user_ids),
    )
    conn.execute(
        f"DELETE FROM community_post_signals WHERE user_id IN ({placeholders})",
        tuple(user_ids),
    )
    conn.execute(
        f"DELETE FROM community_post_reports WHERE reporter_user_id IN ({placeholders})",
        tuple(user_ids),
    )
    conn.execute(
        f"DELETE FROM community_creative_jobs WHERE user_id IN ({placeholders})",
        tuple(user_ids),
    )
    conn.execute(f"DELETE FROM feedback WHERE user_id IN ({placeholders})", tuple(user_ids))
    conn.execute(f"DELETE FROM sessions WHERE user_id IN ({placeholders})", tuple(user_ids))
    conn.execute(f"DELETE FROM users WHERE id IN ({placeholders})", tuple(user_ids))


def _ensure_import_user(
    conn: Any,
    email_prefix: str,
    ordinal: int,
    nickname: str,
    created_at: int,
    used_nicknames: set[str],
) -> dict[str, Any]:
    final_nickname = _choose_unique_nickname(nickname, ordinal=ordinal, used_nicknames=used_nicknames)
    email = f"{email_prefix}_{ordinal:03d}@cammate.local"
    cur = conn.execute(
        """
        INSERT INTO users(email, password_hash, password_salt, nickname, created_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (email, "import_password_hash", "import_password_salt", final_nickname, created_at),
    )
    return {"id": int(cur.lastrowid), "nickname": final_nickname, "email": email}


def _insert_feedback(
    conn: Any,
    user_id: int,
    photo_path: Path,
    metadata: ParsedMetadata,
    created_at: int,
    batch_label: str,
) -> int:
    session_meta = json.dumps(
        {
            "import_batch": batch_label,
            "source_filename": photo_path.name,
            "tags": metadata.tags,
            "primary_category": metadata.primary_category,
        },
        ensure_ascii=False,
    )
    cur = conn.execute(
        """
        INSERT INTO feedback(
            user_id, rating, scene, tip_text, photo_uri,
            is_retouch, review_text, session_meta, created_at
        ) VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?)
        """,
        (
            user_id,
            metadata.rating,
            metadata.scene_type,
            _tip_text_for_category(metadata.primary_category),
            str(photo_path),
            metadata.review_text,
            session_meta,
            created_at,
        ),
    )
    return int(cur.lastrowid)


def _insert_post(
    conn: Any,
    user_id: int,
    feedback_id: int,
    upload_path: Path,
    image_bytes: bytes,
    metadata: ParsedMetadata,
    created_at: int,
) -> int:
    cur = conn.execute(
        """
        INSERT INTO community_posts(
            user_id, feedback_id, image_path, image_blob, image_mime_type, scene_type, place_tag,
            rating, review_text, caption, post_type, source_type,
            relay_parent_post_id, style_template_post_id,
            like_count, comment_count, created_at, moderation_status
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'normal', 'feedback_flow', NULL, NULL, 0, 0, ?, 'published')
        """,
        (
            user_id,
            feedback_id,
            str(upload_path),
            image_bytes,
            "image/jpeg",
            metadata.scene_type,
            metadata.place_tag,
            metadata.rating,
            metadata.review_text,
            metadata.caption,
            created_at,
        ),
    )
    return int(cur.lastrowid)


def _populate_engagement(conn: Any, imported_posts: list[ImportedPost], rng: random.Random) -> None:
    if not imported_posts:
        return

    user_rows = conn.execute("SELECT id, nickname FROM users ORDER BY id").fetchall()
    all_users = [{"id": int(row["id"]), "nickname": str(row["nickname"] or "")} for row in user_rows]
    imported_by_id = {item.user_id: item for item in imported_posts}

    for post in imported_posts:
        like_candidates = [user for user in all_users if user["id"] != post.user_id]
        rng.shuffle(like_candidates)
        # Avoid saturating every imported post at the same ceiling when the
        # target likes exceed the current community size.
        like_ceiling = max(8, len(like_candidates) - rng.randint(2, max(6, len(like_candidates) // 2)))
        target_like_count = min(post.like_count, len(like_candidates), like_ceiling)
        like_time = post.created_at + rng.randint(600, 1800)
        for liker in like_candidates[:target_like_count]:
            conn.execute(
                """
                INSERT OR IGNORE INTO community_post_likes(post_id, user_id, created_at)
                VALUES (?, ?, ?)
                """,
                (post.post_id, liker["id"], like_time),
            )
            like_time += rng.randint(240, 900)

        comment_candidates = [user for user in all_users if user["id"] != post.user_id]
        rng.shuffle(comment_candidates)
        comments = _build_comment_list(post=post, desired_count=post.comment_count)
        for index, text in enumerate(comments):
            commenter = comment_candidates[index % len(comment_candidates)] if comment_candidates else {"id": post.user_id}
            conn.execute(
                """
                INSERT INTO community_post_comments(post_id, user_id, text, created_at)
                VALUES (?, ?, ?, ?)
                """,
                (
                    post.post_id,
                    commenter["id"],
                    text,
                    post.created_at + rng.randint(1800, 3600) + index * rng.randint(300, 900),
                ),
            )


def _build_comment_list(post: ImportedPost, desired_count: int) -> list[str]:
    desired = max(0, desired_count)
    comments = [text for text in post.comments if text.strip()]
    templates = _comment_templates_for_category(post.primary_category)

    index = 0
    while len(comments) < desired and templates:
        template = templates[index % len(templates)]
        comments.append(template.format(place=post.place_tag, nickname=post.nickname))
        index += 1
    return comments[:desired]


def _normalize_primary_category(value: str) -> str:
    raw = value.strip().lower()
    mapping = {
        "portrait": "portrait",
        "people": "portrait",
        "person": "portrait",
        "group": "portrait",
        "landscape": "landscape",
        "travel": "travel",
        "night": "night",
        "food": "food",
        "pet": "pet",
        "flower": "flower",
        "indoor": "indoor",
        "general": "general",
    }
    return mapping.get(raw, "general")


def _map_scene_type(value: str) -> str:
    raw = value.strip().lower()
    if raw in {"portrait", "food", "night", "landscape", "general", "pet", "flower"}:
        return raw
    category = _normalize_primary_category(raw)
    if category in {"portrait", "food", "night", "pet", "flower"}:
        return category
    if category in {"landscape", "travel"}:
        return "landscape"
    return "general"


def _default_place_tag(primary_category: str) -> str:
    return {
        "portrait": "室内合照区",
        "landscape": "湖边观景位",
        "travel": "出游随拍点",
        "night": "夜景灯光位",
        "food": "聚餐餐桌",
        "pet": "日常宠物角落",
        "flower": "春日花景点",
        "indoor": "室内氛围角",
        "general": "日常随拍点",
    }.get(primary_category, "日常随拍点")


def _default_caption(primary_category: str, place_tag: str) -> str:
    return {
        "portrait": f"{place_tag} 这一组氛围感很满，随手一拍都像留住了当天的情绪。",
        "landscape": f"站在 {place_tag} 往外看，画面一下子就被风和空间感打开了。",
        "travel": f"{place_tag} 这类小景很适合做出游记录，回看时会很有记忆点。",
        "night": f"{place_tag} 的光线很会讲故事，按下快门那一刻氛围就有了。",
        "food": f"{place_tag} 这一桌真的太有分享欲了，热闹感和食欲都一起上来了。",
        "pet": f"{place_tag} 抓到这一瞬间就很值，主角的状态特别自然。",
        "flower": f"{place_tag} 的这一点颜色很轻，但一进画面就很出片。",
        "indoor": f"{place_tag} 的层次和暖光都很舒服，特别适合发日常。",
        "general": f"{place_tag} 这一张就很像当天会想留下来的那种瞬间。",
    }.get(primary_category, f"{place_tag} 这一张很适合发进社区。")


def _default_review(primary_category: str, place_tag: str) -> str:
    return {
        "portrait": f"{place_tag} 建议人物别完全站正，肩线和视线稍微错开，画面会更自然。",
        "landscape": f"{place_tag} 这类风景图优先把前景和远景层次留出来，推荐横向展开画面。",
        "travel": f"{place_tag} 更适合保留一点环境信息，照片会比单纯特写更有到此一游的记忆点。",
        "night": f"{place_tag} 建议先保住高光区域，再去微调主体亮度，夜景会更耐看。",
        "food": f"{place_tag} 这类餐桌图尽量保持桌面边缘整洁，让主菜和餐具形成节奏感。",
        "pet": f"{place_tag} 抓拍时优先等眼神和动作同步，宠物图会更有互动感。",
        "flower": f"{place_tag} 可以保留一点枝叶或天空留白，花景会显得更轻更有季节感。",
        "indoor": f"{place_tag} 适合利用室内线条和暖光做层次，照片会更有生活感。",
        "general": f"{place_tag} 这张适合保留环境和主体的关系，社区里会更容易让人停下来多看两眼。",
    }.get(primary_category, f"{place_tag} 这张图的画面关系比较完整。")


def _default_rating(primary_category: str) -> int:
    return {
        "portrait": 5,
        "landscape": 5,
        "travel": 4,
        "night": 5,
        "food": 4,
        "pet": 5,
        "flower": 4,
        "indoor": 4,
        "general": 4,
    }.get(primary_category, 4)


def _default_like_count(primary_category: str) -> int:
    return {
        "portrait": 14,
        "landscape": 11,
        "travel": 9,
        "night": 12,
        "food": 10,
        "pet": 13,
        "flower": 8,
        "indoor": 7,
        "general": 8,
    }.get(primary_category, 8)


def _normalize_nickname(value: str) -> str:
    compact = " ".join(value.strip().split())
    return compact[:20]


def _choose_unique_nickname(nickname: str, ordinal: int, used_nicknames: set[str]) -> str:
    candidates = [nickname] if nickname else []
    if ordinal - 1 < len(_NICKNAME_POOL):
        candidates.append(_NICKNAME_POOL[ordinal - 1])
    candidates.extend(_NICKNAME_POOL)
    candidates.append(f"拍友{ordinal:02d}")

    for candidate in candidates:
        base = _normalize_nickname(candidate)
        if not base:
            continue
        if base not in used_nicknames:
            used_nicknames.add(base)
            return base

    final_name = f"拍友{ordinal:02d}"
    used_nicknames.add(final_name)
    return final_name


def _pick_created_at(captured_at: str, photo_path: Path, index: int) -> int:
    text = captured_at.strip()
    if text:
        try:
            if text.endswith("Z"):
                text = text[:-1] + "+00:00"
            return int(datetime.fromisoformat(text).timestamp())
        except Exception:
            pass
    return int(photo_path.stat().st_mtime) + index * 173


def _normalize_image_bytes(photo_path: Path) -> bytes:
    with Image.open(photo_path) as raw:
        image = ImageOps.exif_transpose(raw).convert("RGB")
        max_side = 1920
        if max(image.size) > max_side:
            image.thumbnail((max_side, max_side), Image.Resampling.LANCZOS)
        output = Path(photo_path.name).suffix.lower()
        mime = "JPEG"
        from io import BytesIO

        buf = BytesIO()
        image.save(buf, format=mime, quality=90, optimize=True)
        data = buf.getvalue()
        if not data:
            raise RuntimeError(f"failed to normalize image: {photo_path}")
        return data


def _save_import_image_bytes(photo_dir: Path, image_name: str, image_bytes: bytes) -> Path:
    upload_dir = PY_ROOT / "uploads" / "community"
    upload_dir.mkdir(parents=True, exist_ok=True)
    sanitized = re.sub(r"[^0-9A-Za-z_\-.一-龥]+", "_", Path(image_name).stem)[:60].strip("_") or "photo"
    target = upload_dir / f"import_{sanitized}.jpg"
    suffix = 1
    while target.exists():
        target = upload_dir / f"import_{sanitized}_{suffix}.jpg"
        suffix += 1
    target.write_bytes(image_bytes)
    return target.resolve()


def _delete_local_file(raw_path: str) -> None:
    path = Path(str(raw_path or "").strip())
    if not str(path):
        return
    try:
        resolved = path.resolve() if path.is_absolute() else (PY_ROOT / path).resolve()
        if resolved.exists():
            resolved.unlink()
    except Exception:
        return


def _clamp_int(value: Any, default: int, min_value: int, max_value: int) -> int:
    try:
        num = int(str(value).strip())
    except Exception:
        num = default
    return max(min_value, min(max_value, num))


if __name__ == "__main__":
    main()
